services:
  async-studio:
    build:
      context: .
      args:
        - DOCUMENT_URL=docs/asyncapi/asyncapi.yaml
    container_name: events-api
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - ./public/docs/asyncapi:/usr/share/nginx/html/docs/asyncapi
